### ISSUE TITLE
No match track ids in playlists

### ISSUE THREAD

**Issue by vmaccatrozzo** [dbis-uibk/ALF200k#1]
Hi,

I would like to use your dataset for an experiment. However, when I tried to get the titles of the tracks in playlists, I realized that there is no match between the tracks id in the playlists.json file and the tracks id in the tracks.json file. 

Would you be so kind to check this? 

Thanks,
Valentina

**Comment by evazangerle** [comment]
Thank you for your feedback. I added the track id to the tracks-file and now you should be able to match playlists and tracks via this id.

**Comment by maccatrozzov** [comment]
Hi!

Do you happen to know why when I try to retrieve information about the playlists through the Spotify API, I get an error back that the playlist ID is not found? I get the same error with user ids, but it works just fine with track ids.

Thanks!
Valentina
