### ISSUE TITLE
Playlists ids are not valid Spotify IDs

### ISSUE THREAD

**Issue by maccatrozzov** [dbis-uibk/ALF200k#14]
Hi!

Do you happen to know why when I try to retrieve information about the playlists through the Spotify API, I get an error back that the playlist ID is not valid? I get the same error with user ids, but it works just fine with track ids.

Thanks!
Valentina

**Comment by evazangerle** [comment]
Dear Valentina,

if I recall correctly, the playlist and user ids are ids generated by us, not the spotify IDs (due to privacy issues).
